[build]
  command = "NODE_OPTIONS=--openssl-legacy-provider npm run generate"
  publish = "dist"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

[build.environment]
  NODE_VERSION = "18"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'self' https://canadianadventurecamp.sanity.studio"
