[build]
  command = "npm run generate"
  publish = "dist"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'self' https://canadianadventurecamp.sanity.studio"
